version: '3.8'

services:
  postgres:
    container_name: challenge-sky-db
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - challenge-net

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      HOST: postgres:5432
      CORS_ALLOWED_ORIGINS: http://localhost,http://127.0.0.1:3000
    networks:
      - challenge-net

volumes:
  postgres_data:

networks:
  challenge-net:
